
name: Pipeline CI/CD
run-name: Pipeline CI/CD executada no ambiente de ${{ vars.STAGE }}
permissions:
  id-token: write
  contents: read
  security-events: write
  

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - closed
  # push:
  #   branches: 
  #     - "main"      
  #     - "develop"     
    paths-ignore: 
      - k8s/deploy/hml/*
      - k8s/deploy/prd*  
  workflow_dispatch:  

  
jobs:
  CI:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.5

  build-dev:
    name: build-dev    
    if: github.ref == 'refs/heads/develop'
    needs: [CI]    
    uses: wallafidevops/desafio-actions-eks/.github/workflows/build.yml@develop
    with:
      environment: dev
    secrets: inherit      

  build-prod:
    name: build-prod  
    if: github.ref == 'refs/heads/main'
    needs: [CI]    
    uses: wallafidevops/desafio-actions-eks/.github/workflows/build.yml@main
    with:
      environment: prod
    secrets: inherit         

  testes-dev:
    name: testes-dev
    if: github.ref == 'refs/heads/develop'   
    needs: [build-dev]
    uses: wallafidevops/desafio-actions-eks/.github/workflows/testes.yml@develop
    with:
      environment: dev   
    secrets: inherit

  testes-prod:
    name: testes-prod
    if: github.ref == 'refs/heads/main'  
    needs: [build-prod]
    uses: wallafidevops/desafio-actions-eks/.github/workflows/testes.yml@main
    with:
      environment: prod   
    secrets: inherit


  release-dev:
    name: release-dev
    if: github.ref == 'refs/heads/develop'
    needs: [testes-dev]
    uses: wallafidevops/desafio-actions-eks/.github/workflows/releases.yml@develop
    with:
      environment: dev   
    secrets: inherit
  
  release-prod:
    name: release-prod
    if: github.ref == 'refs/heads/main'
    needs: [testes-prod]
    uses: wallafidevops/desafio-actions-eks/.github/workflows/releases.yml@main
    with:
      environment: prod   
    secrets: inherit
          


  deploy-dev:
    name: deploy-dev
    if: github.ref == 'refs/heads/develop'
    needs: [release-dev]
    uses: wallafidevops/desafio-actions-eks/.github/workflows/deploy.yml@develop
    with:
      environment: dev
    secrets: inherit      



  deploy-producao:
    name: deploy-producao
    if: github.ref == 'refs/heads/main'
    needs: [release-prod]
    uses: wallafidevops/desafio-actions-eks/.github/workflows/deploy.yml@main
    with:
      environment: prod
    secrets: inherit


