apiVersion: apps/v1
kind: Deployment
metadata:
  name: hml-reviewfilmes
spec:
  replicas: 8
  selector:
    matchLabels:
      app: reviewfilmes
  template:
    metadata:
      labels:
        app: reviewfilmes
    spec:
      containers:
        - name: reviewfilmes
          image: 216989136189.dkr.ecr.us-east-1.amazonaws.com/hml-review-filmes:64
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: '8080'
            - name: ConnectionStrings__DefaultConnection
              value: Host=postgre;Database=reviewfilmes;Username=reviewfilmes;Password=Passw0rd2024!
          ports:
            - containerPort: 8080