name: Build Dockerfile
on: 
    workflow_call:
        inputs:
            environment:
                type: string
                required: true
                description: 'Nome ambiente'

jobs:
  build:
    name: build 
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.300
      - name: executando comando build
        working-directory: ./src
        run: dotnet build Review-Filmes.sln                